// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChoADp48EESoaTQB12dIq90c2aKrTyqTo',
    appId: '1:69222600837:web:bd1ce357168ab8d366d9ec',
    messagingSenderId: '69222600837',
    projectId: 'tg-fatec-4b561',
    authDomain: 'tg-fatec-4b561.firebaseapp.com',
    storageBucket: 'tg-fatec-4b561.appspot.com',
    measurementId: 'G-V1Y3F61R2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx1s9ahU78HxDaw2KdQ_4q4WMiLhmCof0',
    appId: '1:69222600837:android:51b4d58d06a7a82266d9ec',
    messagingSenderId: '69222600837',
    projectId: 'tg-fatec-4b561',
    storageBucket: 'tg-fatec-4b561.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWFY2QAejascaMOMsdyKSdrXj1Zyd6Dys',
    appId: '1:69222600837:ios:817c56f4e96658bc66d9ec',
    messagingSenderId: '69222600837',
    projectId: 'tg-fatec-4b561',
    storageBucket: 'tg-fatec-4b561.appspot.com',
    iosBundleId: 'com.example.app',
  );
}
